apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - limitador-deployment.yaml
  - limitador-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
configMapGenerator:
  - name: limitador-config
    files:
      - files/limits.yaml
