---
# tasks file for deploy-hub-router
- name: Update repo cache
  become: yes
  apt:
    update_cache: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - wireguard
    state: latest

- name: Create the gen key script
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/gen-keys.sh
    content: |
      if [ ! -e /etc/wireguard/public.key ]; then
          wg genkey | sudo tee /etc/wireguard/private.key | wg pubkey | sudo tee /etc/wireguard/public.key
      fi

- name: Copy the verifier script
  copy:
    src: verify-connectivity.sh
    dest: /home/{{ ansible_user }}/
    mode: '0755'

- name: Temporary, remove this one a patch is merged resolving this
  become: yes
  shell: sysctl -w net.ipv4.ip_forward=1

- name: Create Node Keys
  become: yes
  shell: |
    chmod +x /home/{{ ansible_user }}/gen-keys.sh
    /home/{{ ansible_user }}/gen-keys.sh

- name: Register the Public Key for the Node
  become: yes
  shell: cat /etc/wireguard/public.key
  register: PUBLIC_KEY

- name: Register the Private Key for the Node
  become: yes
  shell: cat /etc/wireguard/private.key
  register: PRIVATE_KEY

- name: Download the Apex Agent Binary
  shell: |
    sudo curl {{ apex_binary }} --output /usr/local/sbin/apex
    sudo chmod +x /usr/local/sbin/apex

- name: Attach the Hub Router to the Controller
  become: yes
  shell: |
    APEX_LOGLEVEL=debug nohup apex \
    --public-key={{ PUBLIC_KEY.stdout }} \
    --private-key-file={{ private_key_file }} \
    --controller={{ controller_address }} \
    --controller-password={{ controller_password }} \
    --public-network \
    --zone={{ apex_zone_uuid }} \
    --hub-router > apex-logs.txt 2>&1 &
