apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: nexodus-grafanadatasource
  namespace: nexodus-monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: "nexodus"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated:9090
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
