---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator-controller-manager
  namespace: default
  labels:
    app: grafana-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: grafana-operator-controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: grafana-operator-controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources: {}
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          image: ghcr.io/grafana-operator/grafana-operator:v5.0.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: grafana-operator-controller-manager
      terminationGracePeriodSeconds: 10
