resources:
- crds.yaml
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/grafana-operator/grafana-operator
  newName: ghcr.io/grafana-operator/grafana-operator
  newTag: v5.0.0-rc1
