pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build-workflow-complete
      - label!=hold
    actions:
      merge:
        method: merge