FROM alpine:3.16 as alpine
RUN apk add --no-cache iputils wireguard-tools iptables psmisc
COPY ./dist/apex /bin/apex
ENTRYPOINT [ "/bin/apex" ]

FROM fedora:36 as fedora
RUN dnf update -qy && \
    dnf install --setopt=install_weak_deps=False -qy \
    iputils \
    iproute \
    psmisc \
    procps-ng \
    wireguard-tools \
    iptables \
    hostname \
    && \
    dnf clean all
COPY ./dist/apex /bin/apex
ENTRYPOINT [ "/bin/apex" ]

FROM ubuntu:22.04 as ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qy && \
    apt-get install --no-install-recommends -qy \
    iputils-ping \
    iproute2 \
    wireguard-tools \
    iptables \
    psmisc \
    && \
    apt-get clean
COPY ./dist/apex /bin/apex
ENTRYPOINT [ "/bin/apex" ]
