FROM docker.io/library/node:16-alpine AS builder

WORKDIR /app

COPY ui/package.json .
COPY ui/yarn.lock .
RUN yarn install

ARG VITE_KEYCLOAK_URL=/auth
ARG VITE_KEYCLOAK_REALM=controller
ARG VITE_KEYCLOAK_CLIENT_ID=front-controller
ARG VITE_CONTROLLER_URL=/api

COPY ui .
RUN yarn build

FROM docker.io/nginxinc/nginx-unprivileged:latest
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./ui/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
