FROM docker.io/library/node:16-alpine AS builder

WORKDIR /app

COPY ui/package.json .
COPY ui/package-lock.json .
RUN npm install

COPY ui .
RUN npm run build

FROM docker.io/nginxinc/nginx-unprivileged:latest
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./ui/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
