FROM mcr.microsoft.com/playwright:v1.39.0-jammy

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/cacerts.crt

RUN apt-get update -y \
    && apt-get install -y libnss3-tools \
    && apt-get clean all

COPY --chmod=755 ./hack/update-ca.sh /update-ca.sh
