FROM docker.io/library/golang:1.18-alpine as build

WORKDIR /src
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build \
    -ldflags="-extldflags=-static" \
    -o controller ./cmd/apexcontroller

FROM registry.access.redhat.com/ubi8/ubi

COPY --from=build /src/controller /controller
EXPOSE 8080
ENTRYPOINT [ "/controller" ]
