FROM docker.io/library/golang:1.18-alpine as build

WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build \
    -ldflags="-extldflags=-static" \
    -o controller ./cmd/apexcontroller

FROM scratch

COPY --from=build /src/controller /controller
EXPOSE 8080
ENTRYPOINT [ "/controller" ]
