apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stateful-set.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: nexodus-router
      app.kubernetes.io/instance: nexodus-router
      app.kubernetes.io/name: nexodus-router
