apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-cert
spec:
  secretName: dex-cert
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
      - apex
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - auth.apex.local
  issuerRef:
    name: apex-issuer
    kind: Issuer
