/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsKeyUsage the model 'ModelsKeyUsage'
type ModelsKeyUsage string

// List of models.KeyUsage
const (
	UsageSigning           ModelsKeyUsage = "signing"
	UsageDigitalSignature  ModelsKeyUsage = "digital signature"
	UsageContentCommitment ModelsKeyUsage = "content commitment"
	UsageKeyEncipherment   ModelsKeyUsage = "key encipherment"
	UsageKeyAgreement      ModelsKeyUsage = "key agreement"
	UsageDataEncipherment  ModelsKeyUsage = "data encipherment"
	UsageCertSign          ModelsKeyUsage = "cert sign"
	UsageCRLSign           ModelsKeyUsage = "crl sign"
	UsageEncipherOnly      ModelsKeyUsage = "encipher only"
	UsageDecipherOnly      ModelsKeyUsage = "decipher only"
	UsageAny               ModelsKeyUsage = "any"
	UsageServerAuth        ModelsKeyUsage = "server auth"
	UsageClientAuth        ModelsKeyUsage = "client auth"
	UsageCodeSigning       ModelsKeyUsage = "code signing"
	UsageEmailProtection   ModelsKeyUsage = "email protection"
	UsageSMIME             ModelsKeyUsage = "s/mime"
	UsageIPsecEndSystem    ModelsKeyUsage = "ipsec end system"
	UsageIPsecTunnel       ModelsKeyUsage = "ipsec tunnel"
	UsageIPsecUser         ModelsKeyUsage = "ipsec user"
	UsageTimestamping      ModelsKeyUsage = "timestamping"
	UsageOCSPSigning       ModelsKeyUsage = "ocsp signing"
	UsageMicrosoftSGC      ModelsKeyUsage = "microsoft sgc"
	UsageNetscapeSGC       ModelsKeyUsage = "netscape sgc"
)
