/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsAddServiceNetwork struct for ModelsAddServiceNetwork
type ModelsAddServiceNetwork struct {
	Description    string `json:"description,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
}
