/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsOrganization struct for ModelsOrganization
type ModelsOrganization struct {
	Description string             `json:"description,omitempty"`
	HubZone     bool               `json:"hubZone,omitempty"`
	Id          string             `json:"id,omitempty"`
	Invitations []ModelsInvitation `json:"invitations,omitempty"`
	IpCidr      string             `json:"ipCidr,omitempty"`
	IpCidrV6    string             `json:"ipCidrV6,omitempty"`
	Name        string             `json:"name,omitempty"`
	OwnerID     string             `json:"ownerID,omitempty"`
}
