/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsUserOrganization struct for ModelsUserOrganization
type ModelsUserOrganization struct {
	OrganizationId string     `json:"organization_id,omitempty"`
	Roles          []string   `json:"roles,omitempty"`
	User           ModelsUser `json:"user,omitempty"`
	UserId         string     `json:"user_id,omitempty"`
}
