/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsUpdateDevice struct for ModelsUpdateDevice
type ModelsUpdateDevice struct {
	AdvertiseCidrs          []string         `json:"advertise_cidrs,omitempty"`
	EndpointLocalAddressIp4 string           `json:"endpoint_local_address_ip4,omitempty"`
	Endpoints               []ModelsEndpoint `json:"endpoints,omitempty"`
	Hostname                string           `json:"hostname,omitempty"`
	Revision                int32            `json:"revision,omitempty"`
	SymmetricNat            bool             `json:"symmetric_nat,omitempty"`
}
