/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsAddInvitation struct for ModelsAddInvitation
type ModelsAddInvitation struct {
	OrganizationId string `json:"organization_id,omitempty"`
	UserId         string `json:"user_id,omitempty"`
}
