/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsAddInvitation struct for ModelsAddInvitation
type ModelsAddInvitation struct {
	// The email address of the user to invite (one of email or user_id is required)
	Email          string `json:"email,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	// The user id to invite (one of email or user_id is required)
	UserId string `json:"user_id,omitempty"`
}
