/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsAddOrganization struct for ModelsAddOrganization
type ModelsAddOrganization struct {
	Description     string `json:"description,omitempty"`
	Name            string `json:"name,omitempty"`
	SecurityGroupId string `json:"security_group_id,omitempty"`
}
