/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsWatchEvent struct for ModelsWatchEvent
type ModelsWatchEvent struct {
	Kind  string                 `json:"kind,omitempty"`
	Type  string                 `json:"type,omitempty"`
	Value map[string]interface{} `json:"value,omitempty"`
}
