/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsServiceNetwork struct for ModelsServiceNetwork
type ModelsServiceNetwork struct {
	CaCertificates []string `json:"ca_certificates,omitempty"`
	Description    string   `json:"description,omitempty"`
	Id             string   `json:"id,omitempty"`
	OrganizationId string   `json:"organization_id,omitempty"`
	Revision       int32    `json:"revision,omitempty"`
}
