/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsConflictsError struct for ModelsConflictsError
type ModelsConflictsError struct {
	Error string `json:"error,omitempty"`
	Id    string `json:"id,omitempty"`
}
