/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsNotAllowedError struct for ModelsNotAllowedError
type ModelsNotAllowedError struct {
	Error  string `json:"error,omitempty"`
	Reason string `json:"reason,omitempty"`
}
