/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsCertificateSigningRequest struct for ModelsCertificateSigningRequest
type ModelsCertificateSigningRequest struct {
	// Requested 'duration' (i.e. lifetime) of the Certificate. Note that the issuer may choose to ignore the requested duration, just like any other requested attribute. +optional
	Duration string `json:"duration,omitempty"`
	// Requested basic constraints isCA value. Note that the issuer may choose to ignore the requested isCA value, just like any other requested attribute.  NOTE: If the CSR in the `Request` field has a BasicConstraints extension, it must have the same isCA value as specified here.  If true, this will automatically add the `cert sign` usage to the list of requested `usages`. +optional
	IsCa bool `json:"is_ca,omitempty"`
	// The PEM-encoded X.509 certificate signing request to be submitted to the issuer for signing.  If the CSR has a BasicConstraints extension, its isCA attribute must match the `isCA` value of this CertificateRequest. If the CSR has a KeyUsage extension, its key usages must match the key usages in the `usages` field of this CertificateRequest. If the CSR has a ExtKeyUsage extension, its extended key usages must match the extended key usages in the `usages` field of this CertificateRequest.
	Request string `json:"request,omitempty"`
	// Requested key usages and extended key usages.  NOTE: If the CSR in the `Request` field has uses the KeyUsage or ExtKeyUsage extension, these extensions must have the same values as specified here without any additional values.  If unset, defaults to `digital signature` and `key encipherment`. +optional
	Usages []ModelsKeyUsage `json:"usages,omitempty"`
}
