/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsUpdateServiceNetwork struct for ModelsUpdateServiceNetwork
type ModelsUpdateServiceNetwork struct {
	Description string `json:"description,omitempty"`
}
