/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ModelsTunnelIP struct for ModelsTunnelIP
type ModelsTunnelIP struct {
	// IP address and port of the endpoint.
	Address string `json:"address,omitempty"`
	// VPC CIDR this address was allocated from
	Cidr string `json:"cidr,omitempty"`
}
