apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.35.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: WEB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-id
                  optional: false
            - name: WEB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-secret
                  optional: false
            - name: CLI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: cli-client-id
                  optional: false
          args:
            - dex
            - serve
            - /etc/dex/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/dex
      volumes:
        - name: config
          configMap:
            name: dex
      restartPolicy: Always
