apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
commonLabels:
  app.kubernetes.io/component: ipam
  app.kubernetes.io/instance: ipam
  app.kubernetes.io/name: ipam

configMapGenerator:
  - name: ipam
    literals:
      - GOIPAM_PG_SSLMODE=require
