apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apex
resources:
  - apiproxy
  - apiserver
  - backend-cli
  - backend-web
  - dex
  - frontend
  - ipam
  - goff-proxy
commonLabels:
  app.kubernetes.io/part-of: apex
