{
 "title": "Apiserver",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "nexodus, nexodus-qa" }
  ]
 },
 "panels": [
  {
   "title": "Envoy Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (envoy_cluster_upstream_rq_active)"
    }
   ]
  },
  {
   "title": "Envoy Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq[5m]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_duration_seconds_count{namespace=\"${namespace}\"}[5m])"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_size_bytes_count{namespace=\"${namespace}\"}[5m])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_component=\"apiserver\",namespace=\"${namespace}\"}"
    }
   ]
  }
 ]
}