apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexodus-auth-cert
spec:
  secretName: nexodus-auth-cert
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  subject:
    organizations:
      - nexodus
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - auth.try.nexodus.127.0.0.1.nip.io
  issuerRef:
    name: nexodus-issuer
    kind: Issuer
