---
title: Apexd State Machine
---
stateDiagram-v2
    [*] --> IDLE 
    IDLE --> AUTH: "login"
    AUTH --> READY: "login_success"
    AUTH --> IDLE: "login_failed"
    READY --> PEERING: "start"
    PEERING --> READY: "stop"
    READY --> IDLE: "not_authenticated"
    PEERING --> IDLE: "not_authenticated"
