/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelsInternalServerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsInternalServerError{}

// ModelsInternalServerError struct for ModelsInternalServerError
type ModelsInternalServerError struct {
	Error   *string `json:"error,omitempty"`
	TraceId *string `json:"trace_id,omitempty"`
}

// NewModelsInternalServerError instantiates a new ModelsInternalServerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsInternalServerError() *ModelsInternalServerError {
	this := ModelsInternalServerError{}
	return &this
}

// NewModelsInternalServerErrorWithDefaults instantiates a new ModelsInternalServerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsInternalServerErrorWithDefaults() *ModelsInternalServerError {
	this := ModelsInternalServerError{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ModelsInternalServerError) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsInternalServerError) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ModelsInternalServerError) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ModelsInternalServerError) SetError(v string) {
	o.Error = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *ModelsInternalServerError) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsInternalServerError) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *ModelsInternalServerError) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *ModelsInternalServerError) SetTraceId(v string) {
	o.TraceId = &v
}

func (o ModelsInternalServerError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsInternalServerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	return toSerialize, nil
}

type NullableModelsInternalServerError struct {
	value *ModelsInternalServerError
	isSet bool
}

func (v NullableModelsInternalServerError) Get() *ModelsInternalServerError {
	return v.value
}

func (v *NullableModelsInternalServerError) Set(val *ModelsInternalServerError) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsInternalServerError) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsInternalServerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsInternalServerError(val *ModelsInternalServerError) *NullableModelsInternalServerError {
	return &NullableModelsInternalServerError{value: val, isSet: true}
}

func (v NullableModelsInternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsInternalServerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
