/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelsSecurityGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsSecurityGroup{}

// ModelsSecurityGroup struct for ModelsSecurityGroup
type ModelsSecurityGroup struct {
	Description   *string              `json:"description,omitempty"`
	Id            *string              `json:"id,omitempty"`
	InboundRules  []ModelsSecurityRule `json:"inbound_rules,omitempty"`
	OutboundRules []ModelsSecurityRule `json:"outbound_rules,omitempty"`
	Revision      *int32               `json:"revision,omitempty"`
	VpcId         *string              `json:"vpc_id,omitempty"`
}

// NewModelsSecurityGroup instantiates a new ModelsSecurityGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsSecurityGroup() *ModelsSecurityGroup {
	this := ModelsSecurityGroup{}
	return &this
}

// NewModelsSecurityGroupWithDefaults instantiates a new ModelsSecurityGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsSecurityGroupWithDefaults() *ModelsSecurityGroup {
	this := ModelsSecurityGroup{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsSecurityGroup) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsSecurityGroup) SetId(v string) {
	o.Id = &v
}

// GetInboundRules returns the InboundRules field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetInboundRules() []ModelsSecurityRule {
	if o == nil || IsNil(o.InboundRules) {
		var ret []ModelsSecurityRule
		return ret
	}
	return o.InboundRules
}

// GetInboundRulesOk returns a tuple with the InboundRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetInboundRulesOk() ([]ModelsSecurityRule, bool) {
	if o == nil || IsNil(o.InboundRules) {
		return nil, false
	}
	return o.InboundRules, true
}

// HasInboundRules returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasInboundRules() bool {
	if o != nil && !IsNil(o.InboundRules) {
		return true
	}

	return false
}

// SetInboundRules gets a reference to the given []ModelsSecurityRule and assigns it to the InboundRules field.
func (o *ModelsSecurityGroup) SetInboundRules(v []ModelsSecurityRule) {
	o.InboundRules = v
}

// GetOutboundRules returns the OutboundRules field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetOutboundRules() []ModelsSecurityRule {
	if o == nil || IsNil(o.OutboundRules) {
		var ret []ModelsSecurityRule
		return ret
	}
	return o.OutboundRules
}

// GetOutboundRulesOk returns a tuple with the OutboundRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetOutboundRulesOk() ([]ModelsSecurityRule, bool) {
	if o == nil || IsNil(o.OutboundRules) {
		return nil, false
	}
	return o.OutboundRules, true
}

// HasOutboundRules returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasOutboundRules() bool {
	if o != nil && !IsNil(o.OutboundRules) {
		return true
	}

	return false
}

// SetOutboundRules gets a reference to the given []ModelsSecurityRule and assigns it to the OutboundRules field.
func (o *ModelsSecurityGroup) SetOutboundRules(v []ModelsSecurityRule) {
	o.OutboundRules = v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetRevision() int32 {
	if o == nil || IsNil(o.Revision) {
		var ret int32
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetRevisionOk() (*int32, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given int32 and assigns it to the Revision field.
func (o *ModelsSecurityGroup) SetRevision(v int32) {
	o.Revision = &v
}

// GetVpcId returns the VpcId field value if set, zero value otherwise.
func (o *ModelsSecurityGroup) GetVpcId() string {
	if o == nil || IsNil(o.VpcId) {
		var ret string
		return ret
	}
	return *o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSecurityGroup) GetVpcIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcId) {
		return nil, false
	}
	return o.VpcId, true
}

// HasVpcId returns a boolean if a field has been set.
func (o *ModelsSecurityGroup) HasVpcId() bool {
	if o != nil && !IsNil(o.VpcId) {
		return true
	}

	return false
}

// SetVpcId gets a reference to the given string and assigns it to the VpcId field.
func (o *ModelsSecurityGroup) SetVpcId(v string) {
	o.VpcId = &v
}

func (o ModelsSecurityGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsSecurityGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InboundRules) {
		toSerialize["inbound_rules"] = o.InboundRules
	}
	if !IsNil(o.OutboundRules) {
		toSerialize["outbound_rules"] = o.OutboundRules
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	if !IsNil(o.VpcId) {
		toSerialize["vpc_id"] = o.VpcId
	}
	return toSerialize, nil
}

type NullableModelsSecurityGroup struct {
	value *ModelsSecurityGroup
	isSet bool
}

func (v NullableModelsSecurityGroup) Get() *ModelsSecurityGroup {
	return v.value
}

func (v *NullableModelsSecurityGroup) Set(val *ModelsSecurityGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsSecurityGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsSecurityGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsSecurityGroup(val *ModelsSecurityGroup) *NullableModelsSecurityGroup {
	return &NullableModelsSecurityGroup{value: val, isSet: true}
}

func (v NullableModelsSecurityGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsSecurityGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
