/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelsAddServiceNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsAddServiceNetwork{}

// ModelsAddServiceNetwork struct for ModelsAddServiceNetwork
type ModelsAddServiceNetwork struct {
	Description    *string `json:"description,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
}

// NewModelsAddServiceNetwork instantiates a new ModelsAddServiceNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsAddServiceNetwork() *ModelsAddServiceNetwork {
	this := ModelsAddServiceNetwork{}
	return &this
}

// NewModelsAddServiceNetworkWithDefaults instantiates a new ModelsAddServiceNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsAddServiceNetworkWithDefaults() *ModelsAddServiceNetwork {
	this := ModelsAddServiceNetwork{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsAddServiceNetwork) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAddServiceNetwork) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsAddServiceNetwork) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsAddServiceNetwork) SetDescription(v string) {
	o.Description = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ModelsAddServiceNetwork) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAddServiceNetwork) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ModelsAddServiceNetwork) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *ModelsAddServiceNetwork) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

func (o ModelsAddServiceNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsAddServiceNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	return toSerialize, nil
}

type NullableModelsAddServiceNetwork struct {
	value *ModelsAddServiceNetwork
	isSet bool
}

func (v NullableModelsAddServiceNetwork) Get() *ModelsAddServiceNetwork {
	return v.value
}

func (v *NullableModelsAddServiceNetwork) Set(val *ModelsAddServiceNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsAddServiceNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsAddServiceNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsAddServiceNetwork(val *ModelsAddServiceNetwork) *NullableModelsAddServiceNetwork {
	return &NullableModelsAddServiceNetwork{value: val, isSet: true}
}

func (v NullableModelsAddServiceNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsAddServiceNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
