apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-web
      app.kubernetes.io/instance: backend-web
      app.kubernetes.io/name: backend-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-web
        app.kubernetes.io/instance: backend-web
        app.kubernetes.io/name: backend-web
    spec:
      containers:
        - name: backend-web
          image: quay.io/go-oidc-agent/go-oidc-agent:b98e1621e73404c5de21f47c7c5e6fab091e5d17
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: DEBUG
            - name: OIDC_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: OIDC_PROVIDER
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-id
                  optional: false
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-secret
                  optional: false
            - name: REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: REDIRECT_URL
            - name: ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: ORIGINS
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: DOMAIN
            - name: BACKEND
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: BACKEND
            - name: GOFF_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-web
                  key: GOFF_PROXY_URL
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
