#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 28d6ccc6c96acc91e474ea619c19b60d57ce6e6e
  - name: quay.io/nexodus/envsubst
    newTag: 28d6ccc6c96acc91e474ea619c19b60d57ce6e6e
  - name: quay.io/nexodus/frontend
    newTag: 28d6ccc6c96acc91e474ea619c19b60d57ce6e6e
  - name: quay.io/nexodus/go-ipam
    newTag: 28d6ccc6c96acc91e474ea619c19b60d57ce6e6e
