#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: a340780bfc68e84da195e2831ecf857caa2eef63
  - name: quay.io/nexodus/envsubst
    newTag: a340780bfc68e84da195e2831ecf857caa2eef63
  - name: quay.io/nexodus/frontend
    newTag: a340780bfc68e84da195e2831ecf857caa2eef63
  - name: quay.io/nexodus/go-ipam
    newTag: a340780bfc68e84da195e2831ecf857caa2eef63
