#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: f9f79190e68851df5ad5b37a2eff6e137206784e
  - name: quay.io/nexodus/envsubst
    newTag: f9f79190e68851df5ad5b37a2eff6e137206784e
  - name: quay.io/nexodus/frontend
    newTag: f9f79190e68851df5ad5b37a2eff6e137206784e
  - name: quay.io/nexodus/go-ipam
    newTag: f9f79190e68851df5ad5b37a2eff6e137206784e
