#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 91c3b6696d3faf8611205a1b2cd050ce8af446e2
  - name: quay.io/nexodus/envsubst
    newTag: 91c3b6696d3faf8611205a1b2cd050ce8af446e2
  - name: quay.io/nexodus/frontend
    newTag: 91c3b6696d3faf8611205a1b2cd050ce8af446e2
  - name: quay.io/nexodus/go-ipam
    newTag: 91c3b6696d3faf8611205a1b2cd050ce8af446e2
