#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 4f10b81b96064d48863cf4273576e38459d7a2d7
  - name: quay.io/nexodus/envsubst
    newTag: 4f10b81b96064d48863cf4273576e38459d7a2d7
  - name: quay.io/nexodus/frontend
    newTag: 4f10b81b96064d48863cf4273576e38459d7a2d7
  - name: quay.io/nexodus/go-ipam
    newTag: 4f10b81b96064d48863cf4273576e38459d7a2d7
