apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dev
  - stateful-set.yaml
  - service.yaml

namespace: apex

configMapGenerator:
  - name: ipam
    behavior: merge
    literals:
      - GOIPAM_PG_SSLMODE=disable

  - name: apiserver
    behavior: merge
    literals:
      - APEX_DB_SSLMODE=disable

secretGenerator:
  - name: postgres
    literals:
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/pgdata

  - name: database-pguser-apiserver
    literals:
      - host=postgres
      - port=5432
      - user=apiserver
      - password=password
      - dbname=apiserver

  - name: database-pguser-ipam
    literals:
      - host=postgres
      - port=5432
      - user=ipam
      - password=password
      - dbname=ipam

  - name: database-pguser-keycloak
    literals:
      - host=postgres
      - port=5432
      - user=keycloak
      - password=password
      - dbname=keycloak

patchesStrategicMerge:
  - |-
    $patch: delete
    apiVersion: postgres-operator.crunchydata.com/v1beta1
    kind: PostgresCluster
    metadata:
      name: database
