# roles get branched from here
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: setup-ec2

- hosts: hubRouterNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-hub-router

- hosts: apexNodes
  vars_files:
    - vars.yml
  roles:
    - role: deploy-mesh
