apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - daemonset.yaml
commonLabels:
  app.kubernetes.io/component: apex-client
  app.kubernetes.io/instance: apex-client
  app.kubernetes.io/name: apex-client
