apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    cert-manager.io/issuer: nexodus-issuer
spec:
  tls:
    - hosts:
        - try.nexodus.127.0.0.1.nip.io
      secretName: nexodus-frontend-cert
  rules:
    - host: try.nexodus.127.0.0.1.nip.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: apiproxy
                port:
                  number: 8080
