---
# tasks file for stop-apex-agent
- name: Kill any existing apexd process from previous runs
  become: yes
  shell: |
    sudo killall apexd 2> /dev/null
  ignore_errors: yes

- name: Delete wg0
  become: yes
  shell: |
    sudo ip link del wg0
  ignore_errors: yes
