name: ci-e2e-tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    name: e2e-integration
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deployment: ["wireguard", "fedora-wireguard"]
    env:
      JOB_NAME: "jaywalk-e2e-${{ matrix.deployment }}"
      DEPLOYMENT: ${{ matrix.deployment }}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build and Install Binaries
      run: |
        go install ./...

    - name: Run e2e
      run: make OS_IMAGE=quay.io/networkstatic/${{ matrix.DEPLOYMENT }} run-ci-e2e
