name: image-build

on:
  push:
    branches: [ main ]

env:
  REGISTRY: quay.io
  REPOSITORY: apex
  APISERVER_IMAGE_NAME: apiserver
  APISERVER_UI_IMAGE_NAME: frontend
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    environment: image-repositories
    steps:
    - uses: actions/checkout@v2

    - name: Login to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

    - name: Build apiserver image
      id: build-apiserver
      uses: redhat-actions/buildah-build@v2
      with:
        image: apiserver
        tags: latest ${{ github.sha }} ${{github.ref_name}}
        containerfiles: |
          ./Containerfile.apiserver

    - name: Push apiserver to quay.io/
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-apiserver.outputs.image }}
        tags: ${{ steps.build-apiserver.outputs.tags }}
        registry: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}

    - name: Build frontend image
      id: build-frontend
      uses: redhat-actions/buildah-build@v2
      with:
        image: frontend
        tags: latest ${{ github.sha }} ${{github.ref_name}}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        containerfiles: |
          ./Containerfile.frontend

    - name: Push frontend to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-frontend.outputs.image }}
        tags: ${{ steps.build-frontend.outputs.tags }}
        registry: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
